name: CSHomes
version: '1.0.0'
main: net.bitbylogic.cshomes.CSHomes
api-version: '1.21'
authors: [ BitByLogic ]
commands:
  cshomes:
    aliases: [ csh ]
  home:
    aliases: [ homes ]
  sethome:
  delhome:
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.3.20-RC"
  - "com.google.code.gson:gson:2.10.1"
  - "com.zaxxer:HikariCP:5.0.1"
  - "org.xerial:sqlite-jdbc:3.46.0.0"
  - "io.prometheus:simpleclient:0.16.0"
  - "com.github.ben-manes.caffeine:caffeine:3.2.3"
  - "org.redisson:redisson:4.1.0"
